### ISSUE TITLE
odd-unstable/even-stable style of versioning is dropped in Linux kernel

### ISSUE THREAD

**Issue by jserv** [itri-sofa/sofa#2]
The file `release_notes.txt` mentions the following policy on versions:
> Our SOFA starts with 1.0.0 version and follows the rule of Linux Kernel release.

However, such odd-unstable/even-stable style of versioning is already dropped by Linux kernel. Thus, it is not an effective role model to refer.

**Comment by nmra** [comment]
Thanks jserv, we will remove "and follows the rule of Linux Kernel release" at release_notes.txt
