### ISSUE TITLE
Clarify license terms for third-party packages

### ISSUE THREAD

**Issue by jserv** [itri-sofa/sofa#3]
Not every piece of code is written by ITRI. For example, the files in directory `src_miscComp/sofa_monitor/SOFAUI/web/jLego/js/addOns/jQuery` are indeed from external jQuery, which is licensed in [MIT-style licensing terms](https://jquery.org/license/). The top-level documentation should clarify and address the third-party packages.

**Comment by nmra** [comment]
Thanks jserv, we will re-examine the license terms and fix the wrong part
