### ISSUE TITLE
Uncertain license terms for sofa kernel module

### ISSUE THREAD

**Issue by jserv** [itri-sofa/sofa#4]
The source file `src/sofa_main/sofa_module_init.c` declares itself as Apache License v2. However, by the end of this file, the kernel module are about to be registered as GPL via the macro `MODULE_LICENSE("GPL")`. The incompatibility between GPLv2/v3 and Apache License were discussed here: https://www.apache.org/licenses/GPL-compatibility.html

Therefore, the current implementation causes the uncertainty regarding licensing terms in sofa module for Linux kernel.

**Comment by peter-huang0402** [comment]
Thanks again. We might need a internal discuss on this issue tomorrow. Maybe we just remove all GPL license and keep Apache License v2 on SOFA.

**Comment by jserv** [comment]
Check [Linux kernel licensing rules](https://www.kernel.org/doc/html/latest/process/license-rules.html) for details.
You might have to apply dual-licensing model. Example from the kernel for license expression in dual licensed file:
* SPDX-License-Identifier: GPL-2.0 OR Apache-2.0

The license described in the COPYING file applies to the kernel source as a whole. You have to make sure the compatibility with GPLv2.
