### ISSUE TITLE
Missing NOTICE file for copyright ownership

### ISSUE THREAD

**Issue by jserv** [itri-sofa/sofa#5]
Each source file contains the ASF notice:
> Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information regarding copyright ownership.

However, there is no `NOTICE` file, which should contain the copyright owner information.
Example in Apache Impala: https://github.com/apache/impala/blob/master/NOTICE.txt

**Comment by peter-huang0402** [comment]
Thanks a lot. We will add NOTICE file on SOFA project and put ASF notice in each source file.

**Comment by peter-huang0402** [comment]
The project is our own software and not an APACHE one, so we can just refer to this boilerplate notice which APACHE indicates without an extra NOTICE file.

http://www.apache.org/foundation/license-faq.html#Apply-My-Software
https://opensource.stackexchange.com/questions/7872/how-to-properly-assemble-notice-file-for-new-software-under-apache-license-2-0
